version: '3.8'

services:
  slack-bot:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - DIFY_API_KEY=${DIFY_API_KEY}
      - SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - DIFY_API_URL=${DIFY_API_URL}
    volumes:
      - ./logs:/app/logs
      - .:/app
    networks:
      - bot-network
    restart: unless-stopped
    depends_on:
      dify-api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://dify-api:8080/health')"]
      interval: 30s
      timeout: 10s
      retries: 3

  dify-api:
    image: dify/dify-api:latest
    environment:
      - API_URL=${DIFY_API_URL}
    networks:
      - bot-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "8080:8080"

networks:
  bot-network:
    driver: bridge

volumes:
  logs:
    driver: local