services:
  slack-bot:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - DIFY_API_KEY=${DIFY_API_KEY}
      - SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - DIFY_API_URL=${DIFY_API_URL}
    volumes:
      - ./logs:/app/logs
      - .:/app
    networks:
      - bot-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('${DIFY_API_URL}/health')"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  bot-network:
    driver: bridge

volumes:
  logs:
    driver: local